### ISSUE TITLE
Can't check config after adding cooker

### ISSUE THREAD

**Issue by vmax77** [syssi/xiaomi_cooker#10]
Hi,

I added the xiaomi_cooker files in the custom components folder, and then added the following in the configuration.yaml : 

`#Xiaomi Cooker
xiaomi_cooker:
  name: Xiaomi Rice Cooker
  host: 192.168.42.58
  token: 1956e85c1a21c9576d7c980f07faa
  model: chunmi.cooker.normal2`

After adding when I go to HomeAssisstant, and Check Config, it seems to be checking forever. 

Would it possible to get some help please?

**Comment by syssi** [comment]
Please care about the indents:

```
xiaomi_miio_cooker:
  name: Xiaomi Rice Cooker
  host: 192.168.130.88
  token: b7c4a758c251955d2c24b1d9e41ce47d
  model: chunmi.cooker.normal2
```
