### ISSUE TITLE
Sensors not working since upgrading to 0.2.1

### ISSUE THREAD

**Issue by Gio76** [syssi/xiaomi_cooker#22]
Since Upgrading to version 0.2.1, none of my sensors are working anymore They are all showing as 'unknown':

![image](https://user-images.githubusercontent.com/26906928/97659445-9d892600-1aa1-11eb-86b3-a9ec9bacb7c8.png)

This is my configuration:

```
xiaomi_miio_cooker:
  name: Rice Cooker
  host: 192.168.86.48
  token: 892******************************
  model: chunmi.cooker.normal2
```

Furthermore, in the documentation, it's specified that when calling the start/stop service you need to specify the entity_id:

![image](https://user-images.githubusercontent.com/26906928/97659655-12f4f680-1aa2-11eb-9cd2-92b24c280812.png)

However, I don't seem to have any entity_id's related to the rice cooker, only the sensors.

Any suggestions on how to fix this?
