### ISSUE TITLE
Temperature is not gathered if the device is idle

### ISSUE THREAD

**Issue by thedeemling** [syssi/xiaomi_cooker#48]
I think it worked correctly earlier - the device was ~20 degrees when idle. Now, after cooking, the temperature just stops being recorded:
![image](https://user-images.githubusercontent.com/82749218/163545320-40bbfcba-f3e1-416a-9de7-db7f98c836fd.png)

What is weird - sometimes it works, sometimes not:
![image](https://user-images.githubusercontent.com/82749218/163545451-4e19c7c6-f24c-4adb-bf05-8dd6a7b98582.png)

This is way I'm starting to think about it as a bug.

Of course, I would like to have the temperature recorded all the time.

Is there something I did wrong? My configuration:

```yaml
xiaomi_miio_cooker:
  name: Xiaomi Rice Cooker
  host: !env_var XIAOMI_RICE_COOKER
  token: !secret xiaomi_rice_cooker_token
  model: chunmi.cooker.normal2
```

```yaml
        - type: sensor
          entity: sensor.xiaomi_miio_cooker_temperature
          graph: line
          detail: 2
          hours_to_show: 2
```
